           EXEC SQL INCLUDE CLAIM     END-EXEC.

           EXEC SQL INCLUDE COMMERCI  END-EXEC.

           EXEC SQL INCLUDE CUSTOMER  END-EXEC.

           EXEC SQL INCLUDE CUSTOMSE  END-EXEC.

           EXEC SQL INCLUDE ENDOWMEN  END-EXEC.

           EXEC SQL INCLUDE MOTOR     END-EXEC.

           EXEC SQL INCLUDE POLICY    END-EXEC.
